language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator10.0
script:
  - xcodebuild -showsdks
  - xcodebuild -project Blurry.xcodeproj -scheme 'Debug' -sdk $IOS_SDK build analyze
